### ISSUE TITLE
Packagist version is out of date

### ISSUE THREAD

**Issue by stanlemon** [LRotherfield/Form#9]
1.1.2 is not available on https://packagist.org/packages/lrotherfield/form I am guessing the hook is either not setup or has become disconnected. Can you update this so that new tags trigger updates over on packagist and we can use composer to get the latest version.

**Comment by djcvijic** [comment]
composer.json has a "version" field set to "1.1.0" instead of being updated regularly.
It's best to remove this "version" field since it's safer, you won't need to worry about this happening again.
Fixing it retroactively will probably not work, since the revision tagged with v1.1.2 already has "version": "1.1.0" in composer.json.
The best thing to do would be to make a new branch on that revision, remove the "version" field completely, commit that change, and then move the v1.1.2 tag to that revision.
Please get around to this quickly, the 1.1.2 version is important because in the newest revision backward compatibility is broken for Symfony <= 2.6.

**Comment by LRotherfield** [comment]
@djcvijic I have made a couple of pushes hopefully as you requested, could you have a look please.  Composer config is not my forte

**Comment by djcvijic** [comment]
Everything seems to be working perfectly now. Thank you, and good job!

**Comment by stanlemon** [comment]
Looks good to me :+1:
